language: bash
os: osx
osx_image: xcode9.4

addons:
  homebrew:
    taps: exolnet/homebrew-deprecated
    packages:
      - php@5.6
      - php@7.1
      - php@7.2
      - php@7.3
    update: true

script:
  - ./.travis/clean.sh
  - ./.travis/test.sh
