language: bash
os: osx

addons:
  homebrew:
    taps: exolnet/homebrew-deprecated
    packages:
      - php@7.2
      - php@7.3
      - php@7.4
    update: true

script:
  - ./.travis/clean.sh
  - ./.travis/test.sh
